# Generated by Django 5.1.2 on 2024-11-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_remove_artpiece_categories_artpiece_categories'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'art_piece')},
        ),
    ]
