# Generated by Django 5.1.2 on 2024-11-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artpiece_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='categories',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='categories',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='art_pieces', to='art.category'),
            preserve_default=False,
        ),
    ]
