# Generated by Django 5.1.2 on 2024-11-25 16:43

import VisionaryVaultApp.art.validators
import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_remove_artpiece_categories_artpiece_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='art_image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), VisionaryVaultApp.art.validators.FileSizeValidator(6)], verbose_name='Art Picture'),
        ),
    ]
