# Generated by Django 5.1.2 on 2024-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_artpiece_art_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='title',
            field=models.CharField(default='Untitled Art Piece', max_length=40, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
