# Generated by Django 5.1.2 on 2024-12-02 12:51

import VisionaryVaultApp.art.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_artpiece_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='art_image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[VisionaryVaultApp.art.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), VisionaryVaultApp.art.validators.FileSizeValidator(6)], verbose_name='Art Picture'),
        ),
    ]
